# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - env:
      global:
        - CODECOV_TOKEN="6c71d521-0d6b-42f8-bbba-168f25184a0a"

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - alenaborvenko@gmail.com
    on_success: never # default: change
    on_failure: always # default: always